### PR TITLE
Use the GraphQL API format for heartade/get-bird-follows compatibility

### PR DESCRIPTION
**Pull request by Heartade**

### CODE REVIEW

**Comment by ianklatzco** [comment]
i'm not precisely sure what this changes but i am happy to yolo merge it ^^

**Comment by ianklatzco** [comment]
i'm not precisely sure what this changes but i am happy to yolo merge it ^^

**Comment by Heartade** [comment]
Ouch it means you can now use https://github.com/heartade/get-bird-follows to get follows but you can't use the original api
We should specify it on the webpage I guess

**Comment by ianklatzco** [comment]
yeah!


... which webpage? ^^

**Comment by Heartade** [comment]
> yeah!
> 
> ... which webpage? ^^

The part where this tells users to go to unflwrs! Edited in https://github.com/ianklatzco/twitter-to-bsky/pull/15/commits/c9098fafdc18dcc8817819816be5acdac212a665

**Comment by ianklatzco** [comment]
cool! feel free to PR and i'll redeploy ^^

**Pull request merged**
